version: '3'
services:
  rasa:
    container_name: rasa
    image: rasa/rasa:3.4.0-spacy-en
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - actions
  actions:
    container_name: actions
    build: ./actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    depends_on:
      - meilisearch
  meilisearch:
    container_name: meilisearch
    image: "getmeili/meilisearch:v1.0"
    ports:
      - "7700:7700"
  frontend:
    container_name: frontend
    build: ./interface
    ports:
      - "3000:3000"
    volumes:
      - ./interface:/app
    depends_on:
      - rasa